### ISSUE TITLE
Can't use .delete() on Message queryset

### ISSUE THREAD

**Issue by bobort** [AliLozano/django-messages-extends#25]
I'm trying to delete all the messages in the Message model that have expired. Unfortunately, I keep getting an error: unhashable type: "Message." I'm using Django 2.2.  I wonder if it has something to do with the __eq__ function in the Message model.

```
Traceback (most recent call last):
  File "\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "\rest_framework\views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "\rest_framework\views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "\rest_framework\views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "\rest_framework\decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "C:\project\general\views.py", line 88, in all_messages_for_user
    Message.objects.filter(expires__lt=timezone.now()).delete()
  File "\django\db\models\query.py", line 710, in delete
    collector.collect(del_query)
  File "\django\db\models\deletion.py", line 192, in collect
    reverse_dependency=reverse_dependency)
  File "\django\db\models\deletion.py", line 94, in add
    if obj not in instances:
TypeError: unhashable type: 'Message'

```

**Comment by bobort** [comment]
And it does. I made PR #26.

**Comment by mpasternak** [comment]
Great. Please add a test-case and I'll commit.

**Comment by bobort** [comment]
I've added a test case.

**Comment by mpasternak** [comment]
#26 merged to master, thanks!
